services:
    app:
        build: .
        image: ai2223l1/stock:latest
        networks:
            - main-network
        ports:
          - host_ip: localhost
            published: 3000
            target: 3000
            protocol: tcp
        env_file:
          - .env
        depends_on:
          - db
    db:
        image: postgres:15.0
        restart: unless-stopped
        networks:
          - main-network
        volumes:
          - type: volume
            source: postgres-data
            target: /var/lib/postgresql/data
        ports:
          - host_ip: localhost
            published: 5432
            target: 5432
            protocol: tcp
        env_file:
          - .env

networks:
    main-network:

volumes:
    postgres-data:

