services:
    app:
        build: .
        image: stock:0.1
        networks:
            - main-network
        ports:
          - published: 3000
            target: 3000
        env_file:
          - .env
        depends_on:
          - db
    db:
        image: postgres:15.0
        restart: unless-stopped
        networks:
          - main-network
        volumes:
          - type: volume
            source: postgres-data
            target: /var/lib/postgresql/data
        ports:
          - published: 5432
            target: 5432
        env_file:
          - .env

networks:
    main-network:

volumes:
    postgres-data:

