services:
    app:
        build: .
        image: stock:dev
        networks:
            - main-network
        ports:
          - published: 5173
            target: 5173
          - published: 3000
            target: 3000
        env_file:
          - .env
        depends_on:
          - db
        command: "npm run start:fulldev"
    db:
        image: postgres:15.0
        restart: unless-stopped
        networks:
          - main-network
        volumes:
          - type: volume
            source: postgres-data
            target: /var/lib/postgresql/data
        env_file:
          - .env

networks:
    main-network:

volumes:
    postgres-data:
    source-dir:

