services:
    app:
        image: ai2223l1/stock:latest
        networks:
            - main-network
        ports:
          - published: 3000
            target: 3000
            protocol: tcp
        env_file:
          - .env
        depends_on:
          - db
        labels:
            com.centurylinklabs.watchtower.enable: true
    db:
        image: postgres:15.0
        restart: unless-stopped
        networks:
          - main-network
        volumes:
          - type: volume
            source: postgres-data
            target: /var/lib/postgresql/data
        env_file:
          - .env
    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - TZ=Europe/Warsaw
          - WATCHTOWER_POLL_INTERVAL=30
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_LABEL_ENABLE=true
#         - WATCHTOWER_SCHEDUE="0 3 * * 4"  # Poll every Friday at 3:00 AM

networks:
    main-network:

volumes:
    postgres-data:

